// Generated by https://quicktype.io

export interface Formation {
  id:        number;
  name:      string;
  nombreh:   number;
  cout:      number;
  programme: string;
  ville:     string;
  categorie: string;
  picture:   string;
}
