// Generated by https://quicktype.io

export interface Individu {
  id:              number;
  nom:             string;
  prenom:          string;
  ville:           string;
  email:           string;
  tel:             string;
  dateDeNaissance: string;
}
