// Generated by https://quicktype.io

export interface SendPlanification {
  datedebut:    string;
  datefin:      string;
  title:        string;
  formationId:  number;
  formateurId:  number;
  entrepriseId?: number;
  groupeId?:     number;
}
