// Generated by https://quicktype.io

export interface User {
  id:       number;
  name:     string;
  ville:    string;
  email:    string;
  motcles:  string;
  note:     string;
  password: string;
  roles:    string;
  type:     string;
}
